name: Build and publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      publish_dir: public
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare public directory (copies repo root)
        run: |
          rm -rf public
          mkdir -p public
          shopt -s extglob || true
          # Copy everything except .git and .github to public
          rsync -av --exclude='.git' --exclude='.github' ./ public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
